package vcs

// Commands is the canonical list of all subcommands that every vcs-* backend
// must handle in its dispatch function, even if the implementation is a no-op
// or returns "not supported".
//
// Coreutils-named aliases (mv, rm) are deliberately NOT listed even though
// every backend dispatches them: `vcs --list-commands` feeds the README's
// shell-integration snippet, which defines a shell function per listed
// command, and a generated mv/rm wrapper would shadow the real /bin/mv and
// /bin/rm in the user's shell. Their parity is pinned by per-backend tests
// instead.
var Commands = []string{
	"absorb",
	"add",
	"addremove",
	"amend",
	"annotate",
	"at_tip",
	"base",
	"blame",
	"branch",
	"branches",
	"change",
	"changed",
	"changelog",
	"changes",
	"checkout",
	"commit",
	"commitforce",
	"copy",
	"count",
	"describe",
	"diffedit",
	"diffs",
	"diffstat",
	"drop",
	"evolve",
	"fastforward",
	"fetchtime",
	"fix",
	"goto",
	"graft",
	"graph",
	"histedit",
	"ignore",
	"incoming",
	"lint",
	"map",
	"mergetool",
	"move",
	"next",
	"outgoing",
	"pending",
	"pick",
	"precommit",
	"presubmit",
	"prev",
	"pull",
	"push",
	"rebase",
	"recommit",
	"remove",
	"rename",
	"resolve",
	"restore",
	"revert",
	"review",
	"reword",
	"rootdir",
	"show",
	"split",
	"squash",
	"status",
	"submit",
	"submitforce",
	"track",
	"unamend",
	"uncommit",
	"undo",
	"unknown",
	"unmerged",
	"unpulled",
	"unpushed",
	"untrack",
	"upload",
	"uploadchain",
}
